# Generated by Django 5.1.7 on 2025-04-02 14:17

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='form',
            name='printed',
        ),
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=50, prefix='F', unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
