# Generated by Django 5.1.7 on 2026-01-20 08:35

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_offlinetransaction_formitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Cream', 'Cream'), ('Consumable', 'Consumable'), ('Injection', 'Injection'), ('Infusion', 'Infusion'), ('Inhaler', 'Inhaler'), ('Suspension', 'Suspension'), ('Syrup', 'Syrup'), ('Eye-drop', 'Eye-drop'), ('Ear-drop', 'Ear-drop'), ('Eye-ointment', 'Eye-ointment'), ('Rectal', 'Rectal'), ('Vaginal', 'Vaginal')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pharmacy.form'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=5, max_length=50, prefix='F', unique=True),
        ),
        migrations.AlterModelTable(
            name='form',
            table='pharmacy_form',
        ),
    ]
