# Generated by Django 5.1.7 on 2025-03-23 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item3',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='lpacemaker_drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.lpacemakerdrugs'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ncap_drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.ncapdrugs'),
        ),
        migrations.AddField(
            model_name='cart',
            name='oncology_drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.oncologypharmacy'),
        ),
    ]
