# Generated by Django 5.1.7 on 2025-03-23 12:25

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='form',
            name='printed',
        ),
        migrations.AddField(
            model_name='form',
            name='hospital_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='ncap_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', length=10, max_length=50, prefix='F', unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='form',
            table='pharmacy_form',
        ),
    ]
