# Generated by Django 5.1.7 on 2025-03-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_form_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pharmacy.form'),
        ),
    ]
