# Generated by Django 5.1.7 on 2026-01-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_offlinetransaction_formitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formitem',
            name='drug_type',
            field=models.CharField(choices=[('LPACEMAKER', 'LPACEMAKER'), ('NCAP', 'NCAP'), ('ONCOLOGY', 'ONCOLOGY')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='formitem',
            index=models.Index(fields=['form', 'drug_name'], name='pharmacy_fo_form_id_cd7fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='formitem',
            index=models.Index(fields=['drug_type'], name='pharmacy_fo_drug_ty_abc0af_idx'),
        ),
        migrations.AddIndex(
            model_name='lpacemakerdrugs',
            index=models.Index(fields=['name'], name='pharmacy_lp_name_3fea36_idx'),
        ),
        migrations.AddIndex(
            model_name='lpacemakerdrugs',
            index=models.Index(fields=['stock'], name='pharmacy_lp_stock_f69bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='lpacemakerdrugs',
            index=models.Index(fields=['exp_date'], name='pharmacy_lp_exp_dat_986a70_idx'),
        ),
        migrations.AddIndex(
            model_name='lpacemakerdrugs',
            index=models.Index(fields=['price'], name='pharmacy_lp_price_2e2263_idx'),
        ),
        migrations.AddIndex(
            model_name='ncapdrugs',
            index=models.Index(fields=['name'], name='pharmacy_nc_name_e0a174_idx'),
        ),
        migrations.AddIndex(
            model_name='ncapdrugs',
            index=models.Index(fields=['stock'], name='pharmacy_nc_stock_aaa5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ncapdrugs',
            index=models.Index(fields=['exp_date'], name='pharmacy_nc_exp_dat_92c647_idx'),
        ),
        migrations.AddIndex(
            model_name='ncapdrugs',
            index=models.Index(fields=['price'], name='pharmacy_nc_price_c68182_idx'),
        ),
        migrations.AddIndex(
            model_name='oncologypharmacy',
            index=models.Index(fields=['name'], name='pharmacy_on_name_ed3ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='oncologypharmacy',
            index=models.Index(fields=['stock'], name='pharmacy_on_stock_62f1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='oncologypharmacy',
            index=models.Index(fields=['exp_date'], name='pharmacy_on_exp_dat_fd6747_idx'),
        ),
        migrations.AddIndex(
            model_name='oncologypharmacy',
            index=models.Index(fields=['price'], name='pharmacy_on_price_908fee_idx'),
        ),
    ]
